# Generated by Django 3.2.9 on 2021-11-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Photo_file_name',
            new_name='photo_file_name',
        ),
    ]
